[project]
name = 'hermetica-usdh-contracts'
description = 'A Bitcoin-backed synthetic dollar protocol'
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP3R4F6C1J3JQWWCVZ3S7FRRYPMYG6ZW6RZK31FXY.pyth-oracle-v3'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-oracle-v4'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-withdrawal'

[[project.requirements]]
contract_id = 'SP2VCQJGH7PHP2DJK7Z0V48AGBHQAW3R3ZW1QF4N.ft-trait'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-storage-v4'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-pnau-decoder-v3'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.wormhole-core-v4'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-traits-v2'

[[project.requirements]]
contract_id = 'SP26NGV9AFZBX7XBDBS2C7EC7FCPSAV9PKREQNMVS.borrower-v1' # granite borrower (pyth v4)

[[project.requirements]]
contract_id = 'SPN5AKG35QZSK2M8GAMR4AFX45659RJHDW353HSG.staking-trait-v1'

[[project.requirements]]
contract_id = 'SPN5AKG35QZSK2M8GAMR4AFX45659RJHDW353HSG.staking-silo-trait-v1'

[[project.requirements]]
contract_id = 'SPN5AKG35QZSK2M8GAMR4AFX45659RJHDW353HSG.minting-auto-trait-v1'

[[project.requirements]]
contract_id = 'SPN5AKG35QZSK2M8GAMR4AFX45659RJHDW353HSG.usdh-token-v1'

[[project.requirements]]
contract_id = 'SPN5AKG35QZSK2M8GAMR4AFX45659RJHDW353HSG.susdh-token-v1'

[[project.requirements]]
contract_id = 'SP1A27KFY4XERQCCRCARCYD1CC5N7M6688BSYADJ7.ft-trait'

[[project.requirements]]
contract_id = 'SP1A27KFY4XERQCCRCARCYD1CC5N7M6688BSYADJ7.market-trait'

[[project.requirements]]
contract_id = 'SP1A27KFY4XERQCCRCARCYD1CC5N7M6688BSYADJ7.vault-traits'

# protocol

[contracts.minting-state]
path = 'contracts/usdh/protocol/minting-state-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.controller]
path = 'contracts/usdh/protocol/controller-v1-1.clar'
clarity_version = 2
epoch = 2.5

[contracts.hq]
path = 'contracts/usdh/protocol/hq-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.minting-otc]
path = 'contracts/usdh/protocol/minting-otc-v1-1.clar'
clarity_version = 4
epoch = 3.3

[contracts.minting]
path = 'contracts/usdh/protocol/minting-v1.clar'
clarity_version = 3
epoch = 3.2

[contracts.minting-auto]
path = 'contracts/usdh/protocol/minting-auto-v1-2.clar'
clarity_version = 3
epoch = 3.2

[contracts.minting-auto-state]
path = 'contracts/usdh/protocol/minting-auto-state-v1.clar'
clarity_version = 3
epoch = 3.2

[contracts.redeeming-reserve]
path = 'contracts/usdh/protocol/redeeming-reserve-v1-2.clar'
clarity_version = 2
epoch = 3.2

[contracts.staking]
path = 'contracts/usdh/protocol/staking-v1-1.clar'
clarity_version = 2
epoch = 3.2

[contracts.staking-silo]
path = 'contracts/usdh/protocol/staking-silo-v1-1.clar'
clarity_version = 3
epoch = 3.2

[contracts.staking-reserve]
path = 'contracts/usdh/protocol/staking-reserve-v1.clar'
clarity_version = 3
epoch = 3.2

[contracts.staking-state]
path = 'contracts/usdh/protocol/staking-state-v1.clar'
clarity_version = 3
epoch = 3.2

[contracts.blacklist-susdh]
path = 'contracts/usdh/protocol/blacklist-susdh-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.emergency-recover]
path = 'contracts/usdh/protocol/emergency-recover-v1.clar'
clarity_version = 2
epoch = 2.5

# tokens

[contracts.susdh-token]
path = 'contracts/usdh/tokens/susdh-token-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.usdh-token]
path = 'contracts/usdh/tokens/usdh-token-v1.clar'
clarity_version = 2
epoch = 2.5

# traits

[contracts.sip-010-trait]
path = 'contracts/usdh/traits/sip-010-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.token-migration-trait]
path = 'contracts/usdh/traits/token-migration-trait-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.interim-token-trait]
path = 'contracts/usdh/traits/interim-token-trait-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.staking-trait]
path = 'contracts/usdh/traits/staking-trait-v1.clar'
clarity_version = 3
epoch = 3.2

[contracts.staking-silo-trait]
path = 'contracts/usdh/traits/staking-silo-trait-v1.clar'
clarity_version = 3
epoch = 3.2

[contracts.minting-auto-trait]
path = 'contracts/usdh/traits/minting-auto-trait-v1.clar'
clarity_version = 3
epoch = 3.2

# hbtc protocol

[contracts.blacklist]
path = 'contracts/hbtc/protocol/blacklist-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.controller-hbtc]
path = 'contracts/hbtc/protocol/controller-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.fee-collector]
path = 'contracts/hbtc/protocol/fee-collector-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.hq-hbtc]
path = 'contracts/hbtc/protocol/hq-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.reserve-fund]
path = 'contracts/hbtc/protocol/reserve-fund-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.reserve]
path = 'contracts/hbtc/protocol/reserve-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.state]
path = 'contracts/hbtc/protocol/state-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.trading]
path = 'contracts/hbtc/protocol/trading-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.vault]
path = 'contracts/hbtc/protocol/vault-v1.clar'
clarity_version = 4
epoch = 3.3

# hbtc interfaces

[contracts.hermetica-interface]
path = 'contracts/hbtc/protocol/interfaces/hermetica-interface-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.zest-interface]
path = 'contracts/hbtc/protocol/interfaces/zest-interface-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.granite-interface]
path = 'contracts/hbtc/protocol/interfaces/granite-interface-v1.clar'
clarity_version = 4
epoch = 3.3

# hbtc tokens

[contracts.token-hbtc]
path = 'contracts/hbtc/tokens/token-hbtc.clar'
clarity_version = 4
epoch = 3.3

# hbtc traits

[contracts.vault-trait-v1]
path = 'contracts/hbtc/traits/vault-trait-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.zest-market-trait-v1]
path = 'contracts/hbtc/traits/zest-market-trait-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.zest-vault-trait-v1]
path = 'contracts/hbtc/traits/zest-vault-trait-v1.clar'
clarity_version = 4
epoch = 3.3

[contracts.granite-borrower-trait-v1]
path = 'contracts/hbtc/traits/granite-borrower-trait-v1.clar'
clarity_version = 4
epoch = 3.3

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
use_mainnet_wallets = true
api_url = 'https://api.hiro.so'
initial_height = 3200000
